AdaCore/langkit

langkit/astdoc.py
langkit/common.py
langkit/compile_context.py
langkit/compiled_types.py
langkit/documentation.py
langkit/dsl.py
langkit/expressions/base.py
langkit/expressions/logic.py
langkit/libmanage.py
langkit/names.py
langkit/utils/__init__.py

Note: Langkit is not yet py3 compatible, but this is a small step along the way

Make some changes for py3 compatibility

---

langkit/compile_context.py
langkit/templates/lexer/quex_interface_body_c.mako
langkit/templates/lexer/quex_interface_header_c.mako
langkit/templates/lexer/quex_lexer_spec.mako
langkit/templates/project_file.mako

Allows to link Libadalang and libgpr2 together

Support of multiple generated lexers in same executable

---

langkit/expressions/base.py

This fixes a source of indeterminism during code generation.

RA17-067: Add __repr__ implementation on Try expressions.

---

langkit/support/langkit_support-lexical_env.adb
langkit/support/langkit_support-lexical_env.ads
langkit/support/langkit_support-symbols.adb
langkit/templates/pkg_implementation_body_ada.mako
testsuite/tests/properties/invalid_cond/test.out

RB06-039: Implement lexical_env.get(*)

---

langkit/templates/main_parse_ada.mako

To enhance testing of parser in case of error recovery

Add consistency check option to parse executable

---

langkit/templates/pkg_rewriting_body_ada.mako
langkit/templates/pkg_rewriting_impl_body_ada.mako
langkit/templates/pkg_rewriting_impl_spec_ada.mako

- Remove unwanted warnings about possible aliasing.
- Remove comments that are not relevant anymore.

RB13-018: Miscellaneous changes.

---

langkit/utils/types.py

Call include for each type in the TypeSet that we want to add to self.
TN: S603-021

Fix method update for TypeSet

---

langkit/templates/ocaml_api/module_ocaml.mako

The path to Camomile's standard library, determined _at compile time_
is stored in CamomileLibrary.DefaultConfig, and used at execution
time. As a result, binaries that use Camomile in a naive way
(including our Libadalang OCaml bindings) are not relocatable. Fix this.

S308-026 make binaries that depend on ocaml bindings relocatable

---

langkit/support/langkit_support-lexical_env.adb
testsuite/tests/lexical_envs/env_get_all/main.py
testsuite/tests/lexical_envs/env_get_all/test.out
testsuite/tests/lexical_envs/env_get_all/test.py
testsuite/tests/lexical_envs/env_get_all/test.yaml

In the special scenario where "get" is called with the "null" symbol,
the output was not deterministic. This commit makes sure it is.

S819-034: Fix determinism issue of env get.

---

langkit/templates/ocaml_api/module_ocaml.mako
langkit/templates/ocaml_api/module_sig_ocaml.mako
testsuite/tests/ocaml_api/general/main.ml
testsuite/tests/ocaml_api/general/test.out

Use C function for the implementation of is_equivalent

---

langkit/templates/pkg_implementation_body_ada.mako

Work for AI12-0339 will make this use of Append ambiguous, so use
Append_One to get forward compatible code.
TN: T722-036

Use Append_One instead of Append for containers

---

langkit/templates/project_file.mako

This will be used to "with" libadalang from liblkqllang

SB05-065: extension points for prj file deps

---

langkit/templates/ocaml_api/module_ocaml.mako
langkit/templates/ocaml_api/module_sig_ocaml.mako

Also make Camomile package public in OCaml bindings
TN: SB12-018

Fix camomile issues when used with a relocalized opam

---

contrib/lkt/extensions/src/liblktlang-implementation-extensions.adb
langkit/templates/parsers/pkg_main_body_ada.mako
langkit/templates/pkg_analysis_body_ada.mako
langkit/templates/pkg_common_body_ada.mako
langkit/templates/pkg_implementation_body_ada.mako
langkit/templates/pkg_introspection_body_ada.mako
langkit/templates/pkg_introspection_impl_body_ada.mako
langkit/templates/pkg_lexer_state_machine_body_ada.mako
langkit/templates/struct_types_ada.mako
manage.py

And activate build warnings in liblktlang & libpythonlang

TC14-031: Fix build warnings in templates

---

langkit/templates/ocaml_api/module_ocaml.mako

Switch Pervasives to Stdlib after upgrade to ocaml 4.11.1

---

testsuite/valgrind_supp/ocaml.supp

Update ocaml valgrind suppression file after the upgrade to ocaml 4.11.1

---

langkit/templates/pkg_analysis_body_ada.mako
langkit/templates/pkg_analysis_spec_ada.mako
support/langkit_support-symbols.ads

SB05-065: Expose symbol table in public Ada API

---

langkit/templates/pkg_implementation_body_ada.mako
support/langkit_support-adalog.ads

To account for changes in Libadalang's equations

U329-012, U225-013: Increase default logic resolution timeout

---

doc/kalint.py

doc: Apply stylechecks on kalint.py

---

doc/conf.py

Sync AdaCore's copyright to 2021.

Fix documentation copyright year

---

langkit/lexer/char_set.py

This trivial change follows a5bf08a3.

Add empty line after imports in generated unicode_data.py

---

langkit/lexer/regexp.py

The two removed lines seem to have no effect, and break the refresh of
unicode_data.py.

Remove dependency of lexer/regexp.py to lexer/unicode_data.py

---

README.md

This trivial change follows f2517372.

README: update path to documentation

---

support/langkit_support-diagnostics-output.adb
testsuite/tests/langkit_support/diagnostics_output/main.adb
testsuite/tests/langkit_support/diagnostics_output/test.out
testsuite/tests/langkit_support/diagnostics_output/test.yaml

UA29-022: Fix bug in diagnostics.output

---

manage.py

In particular, it is convenient when working on Lkt to rebuild only
liblktlang. For convenience too, also disable the full rebuild in that
case.
TN: RA22-015

manage.py: make it possible to build only libpythonlang or liblktlang

---

README.md

README.md: update testing instructions wrt. libpythonlang/liblktlang
