setup.py

Older versions of langkit apparently had a utils.py, but it was now broken into several
python files which need to be installed

Need to install the langkit/utils/ package as well

---

langkit/envs.py
langkit/support/langkit_support-lexical_env.adb
langkit/support/langkit_support-lexical_env.ads
langkit/templates/astnode_types_ada.mako
langkit/templates/pkg_implementation_body_ada.mako

Instead of "Transitive" boolean value. Introduce a new value:
Prioritary, which makes a reference explored before parents, but still
not transitive.

Introduce RefKind enum

---

langkit/libmanage.py

When we are enforcing the build of a particular variant
of the library through the setting of LIBRARY_TYPE and XMLADA_BUILD
we need to do the same for GPR_BUILD, as a safeguard against
contradicting environment variables.

S107-049 make build resistant to environment variables

---

langkit/templates/project_file.mako

This will repair automatic loading of GDB helpers (previous commit on
this topic actually missed that).

project_file.mako: add -DDEBUG=1 to C compile switches in debug mode

---

langkit/support/langkit_support-adalog-predicates.ads

This warning appears only for debug builds. Discovery of occurrences is
late because of some wholes in testsuite coverage.

Adalog.Predicates: fix the warning about anonymous access types

---

langkit/compiled_types.py
langkit/templates/astnode_types_ada.mako
langkit/templates/pkg_implementation_body_ada.mako
testsuite/tests/properties/node_env_concrete_subclass/main.py
testsuite/tests/properties/node_env_concrete_subclass/test.out
testsuite/tests/properties/node_env_concrete_subclass/test.py
testsuite/tests/properties/node_env_concrete_subclass/test.yaml

Previous version was overcomplicated and didn't generate proper code for
a concrete subclass of a concrete base class.

Fix Node.Node_Env

---

langkit/support/langkit_support-lexical_env.adb
langkit/support/langkit_support-lexical_env.ads
langkit/templates/pkg_implementation_body_ada.mako
langkit/templates/pkg_implementation_spec_ada.mako
testsuite/tests/langkit_support/lexical_env_equiv/support.ads
testsuite/tests/langkit_support/lexical_env_group/support.ads
testsuite/tests/langkit_support/lexical_env_image/support.ads
testsuite/tests/langkit_support/lexical_env_orphan/support.ads
testsuite/tests/langkit_support/lexical_env_rebound/support.ads

The Is_Stale procedure was missing information to determine if rebindings
from a given rebound_env where still valid or not and would unsoundly
consider them valid all the time.
This fix adds a field to rebound environments indicating the version of
the context at the time the rebound env is created. Is_Stale now compares
this number with the current context version to determine if a cached
rebound_env is stale or not.

S701-037: Fix invalidation of env_getter cache.

---

langkit/ocaml_api.py
testsuite/tests/ocaml_api/general/main.ml
testsuite/tests/ocaml_api/general/test.out
testsuite/tests/ocaml_api/general/test.py

An EnumType has a ctype view, thus, to unwrap it, it is unecessary to
call the unwrap function.
The wrap function was not being affected by the issue.
wrap and unwrap functions are required only if a type does not define a
ctype view. Thus, refactor the code to reflect this.

S924-008 Fix unwrapping of enum types

---

langkit/libmanage.py
langkit/templates/langkit_support_gpr.mako
langkit/templates/project_file.mako

This patch changes all generated project files so that builds for all
library kinds share the same object directories, and thus every unit is
compiled only once (not once for static builds, then once for
relocatable builds, etc.). Always building with -fPIC allows us to do
this as -fPIC is a requirement for relocatable and static-pic builds.
Most generated library users use -fPIC-based builds, so the (limited?)
extra bloat in generated code for static libraries seems to be worth the
reduction of build times.

Always build with -fPIC and share object directories

---

langkit/libmanage.py

Even though do_generate must define a dummy build mode when run
standalone, it should not set it when it is already defined, for
instance when called from do_make. This used to trigger debug builds
through the "make" subcommand in even when --build-mode=prod was passed.

ManageScript.do_generate: do not set the build mode if already set

---

langkit/templates/memoization_ada.mako
langkit/templates/properties/def_ada.mako
testsuite/tests/properties/memoized_unit_loading/extensions/nodes/example/bodies
testsuite/tests/properties/memoized_unit_loading/main.py
testsuite/tests/properties/memoized_unit_loading/test.out
testsuite/tests/properties/memoized_unit_loading/test.py
testsuite/tests/properties/memoized_unit_loading/test.yaml

If memoization table reset happens in the middle of the exceution of a
property, then computings that happened before that reset could change
in later calls, so it is not sound to keep the result of that property
execution.

Do not memoize prop. if mmz. table reset happened during its execution

---

scripts/manage.sh

This ensures that if the version of GNAT has changed, we won't get an
uncaught exception from out of date libraries.

Minor: clean build space for lib*lang before building

---

langkit/diagnostics.py

This was wrong since the addition of column numbers in the Location
class.

RA22-015: fix initialization of Location from python backtraces

---

langkit/libmanage.py

Mac OS X uses DYLD_LIBRARY_PATH instead of LD_LIBRARY_PATH in Linux. This patch helps me build Libadalang on Mac OS using Github Actions and python3.

Try to fix MacOS build

---

langkit/templates/ocaml_api/module_ocaml.mako
langkit/templates/ocaml_api/module_sig_ocaml.mako
langkit/templates/ocaml_api/struct_types_ocaml.mako
testsuite/tests/ocaml_api/general/main.ml
testsuite/tests/ocaml_api/general/test.out

This PR exposes the filename attribute of the analysis units in the Ocaml bindings.
This also fixes memory leaks on the function token_kind_name in module Token.

Expose filename member for analysis unit in Ocaml bindings

---

langkit/templates/ocaml_api/module_ocaml.mako
langkit/templates/ocaml_api/module_sig_ocaml.mako
testsuite/tests/ocaml_api/general/main.ml
testsuite/tests/ocaml_api/general/test.out

This new utility lets a user lookup the deepest node of a given type
containing the specified source location. The returned node is of
the specified type if found, None otherwise.

Add typed lookup utility for Ocaml bindings

---

manage.py

Got the following error when trying to build on Windows
```
Traceback (most recent call last):
File "manage.py", line 103, in <module>
args.func(args, unknown_args)
File "manage.py", line 35, in wrapper
fn(args)
File "manage.py", line 67, in make
m1 = subprocess.Popen(
File "C:\Python38\lib\subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Python38\lib\subprocess.py", line 1308, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```
Windows requires an executable as the first argument, can't get away with relying on a shebang here!
Added the missing executables to the calls, and made one existing one more consistent.

Fix Windows build by using an executable with subprocess calls

---

langkit/ocaml_api.py
langkit/templates/ocaml_api/module_sig_ocaml.mako

Lists that are constructed from sets need to be sorted before returned
for determism.
no-tn-check

OCaml bindings: for determism, add sorting for some lists

---

langkit/support/langkit_support-symbols.adb
testsuite/tests/properties/symbol/extensions/src/pkg.adb
testsuite/tests/properties/symbol/extensions/src/pkg.ads
testsuite/tests/properties/symbol/main.py
testsuite/tests/properties/symbol/test.out
testsuite/tests/properties/symbol/test.py

When symbol canonicalization fails, $.Lexer_Implementation.Force_Symbol
calls Get_Symbol passing to it No_Thin_Symbol, so Get_Symbol needs to
support this case.

Langkit_Support.Symbols: fix Get_Symbol for null symbols

---

langkit/templates/pkg_implementation_body_ada.mako

This removes the previous "Exception_Information" call and replaces it with a manual output that does not rely on binder options.

U127-008: Log symbolic backtrace in PLE_Errors trace.

---

langkit/emitter.py
langkit/ocaml_api.py
langkit/templates/ocaml_api/array_types_ocaml.mako
langkit/templates/ocaml_api/astnode_types_ocaml.mako
langkit/templates/ocaml_api/module_ocaml.mako
langkit/templates/ocaml_api/module_sig_ocaml.mako
langkit/templates/ocaml_api/struct_types_ocaml.mako

Since we can have hundreds of AST nodes in a langkit hierarchy, using recursive modules to represent them can cause stack overflows at compilation. Change the strategy of emitting ocaml bindings to not emit recursive modules.

Remove recursive modules from OCaml bindings

---

doc/kalint.py
doc/tutorial.rst

This patchs updates the langkit tutorial, starting from the `Getting
Started` section. It consists of updating the new file/path names used
by langkit when creating a project and switching some Python code from
version 2 to 3.
It also adds a new file, `kalint.py` to help the reader to correctly
assemble all the pieces of the langit toy interpreter.

Update langkit tutorial

---

contrib/lkt/extensions/src/liblktlang-implementation-extensions.adb
testsuite/tests/contrib/lkt_semantic/builtin_methods/test.lkt
testsuite/tests/contrib/lkt_semantic/builtin_methods/test.out
testsuite/tests/contrib/lkt_semantic/builtin_methods/test.yaml
testsuite/tests/contrib/lkt_semantic/cast/test.out
testsuite/tests/structs/foreign_env_md/test.py

Adding parent and node_env methods to Node specification in order to
make the following test pass:
testsuite/tests/structs/foreign_env_md/expected_concrete_syntax.lkt.
To do so, a new class has also been introduced: LexicalEnv, as well as
it's get method.

U913-020: add parent and node_env Node's builtins to LKT prelude

---

contrib/lkt/language/parser.py
testsuite/tests/contrib/lkt_semantic/invalid_import/test.lkt
testsuite/tests/contrib/lkt_semantic/invalid_import/test.out
testsuite/tests/contrib/lkt_semantic/invalid_import/test.yaml

Properly emit an error message when the file pointed out by an
`import` statement is not found.

U914-006: emit error message on dependency not found

---

contrib/lkt/language/parser.py
contrib/lkt/language/prelude.lkt
testsuite/tests/contrib/lkt_semantic/advanced_calls/test.lkt
testsuite/tests/contrib/lkt_semantic/advanced_calls/test.out
testsuite/tests/contrib/lkt_semantic/advanced_calls/test.yaml
testsuite/tests/contrib/lkt_semantic/array_list_methods/test.out
testsuite/tests/contrib/lkt_semantic/builtin_methods/test.lkt
testsuite/tests/contrib/lkt_semantic/builtin_methods/test.out
testsuite/tests/contrib/lkt_semantic/call_non_callable/test.lkt
testsuite/tests/contrib/lkt_semantic/call_non_callable/test.out
testsuite/tests/contrib/lkt_semantic/call_non_callable/test.yaml
testsuite/tests/contrib/lkt_semantic/call_non_static_decl/test.lkt
testsuite/tests/contrib/lkt_semantic/call_non_static_decl/test.out
testsuite/tests/contrib/lkt_semantic/call_non_static_decl/test.yaml
testsuite/tests/contrib/lkt_semantic/dot_call_invalid/test.out

This fixes several bugs in the call decl/type resolution mechanism
* Generally make `called_decl` only return a called decl when there is
one for the specific callexpr. Before, for nested call expressions
like `a()()()` it would return the sub call-expression called decl.
* Make `expr_context_free_type` compute the type even when there is no
called declaration

RA22-015: Fix call decl/type resolution

---

testsuite/tests/properties/equality/test.py
testsuite/tests/properties/lower_dispatch_rewrite/test.py

The error reported in this TN doesn't exist anymore, so just turn on the semantic checks here.

U920-003: enable more semantic checks

---

langkit/templates/properties/helpers.mako

Libadalang debug builds are failing because of a style check error.

UA26-008: Fix code generation's style

---

contrib/lkt/language/parser.py
testsuite/tests/contrib/lkt_semantic/decl_block_correctness/test.lkt
testsuite/tests/contrib/lkt_semantic/decl_block_correctness/test.out
testsuite/tests/contrib/lkt_semantic/decl_block_correctness/test.yaml

In order to forbid the use of invalid declaration in the declaration
block of a type declaration, e.g.: StructDecl, EnumClassDecl,
ClassDecl, EnumTypeDecl, and TraitDecl, this patch implements
``check_correctness_pre`` for each of these declarations.
TN: UA20-050

UA20-050: Lkt: reject invalid items in decl lists inside TypeDecl nodes

---

contrib/lkt/language/parser.py
testsuite/tests/contrib/lkt_semantic/property_error/test.lkt
testsuite/tests/contrib/lkt_semantic/property_error/test.out

Ensure that PropertyError is called through the raise keyword.
TN: U928-029

Lkt: emit an error if PropertyError is called without raise

---

contrib/lkt/language/parser.py
testsuite/tests/contrib/lkt_semantic/property_error/test.lkt
testsuite/tests/contrib/lkt_semantic/property_error/test.out

This patch allows to forbid the use of PropertyError as a type,
and enforces that ``raise`` can only calls a ``PropertyError()``.

Lkt: add more PropertyError constraints

---

langkit/compiled_types.py

This expression is needed in Libadalang for the work on predefined
operators synthesis in order to synthesize nodes that derives from Expr,
as those have a `logic_vars` field with type `Address`.

UB16-053: Allow ``No(T.Address)`` expression in properties DSL.

---

contrib/lkt/language/parser.py
testsuite/tests/contrib/lkt_semantic/bin_op_cf_type/test.lkt
testsuite/tests/contrib/lkt_semantic/bin_op_cf_type/test.out
testsuite/tests/contrib/lkt_semantic/generic_fn_instantiation/test.out

Add a test case in ``BinOp.expr_context_free_type`` in order to try to
infer non-boolean operators type from the operands, such as:
```
val x: Array[Int] = [1, 2, 3]
val a = x & x
```

Lkt: improve BinOp type resolution

---

contrib/lkt/extensions/mains/lkt_toolbox.adb
contrib/lkt/language/parser.py
testsuite/tests/contrib/lkt_semantic/ambiguous_type/test.lkt
testsuite/tests/contrib/lkt_semantic/ambiguous_type/test.out
testsuite/tests/contrib/lkt_semantic/base_test/test.lkt
testsuite/tests/contrib/lkt_semantic/base_test/test.out
testsuite/tests/contrib/lkt_semantic/erroneous_component_access/test.lkt
testsuite/tests/contrib/lkt_semantic/erroneous_component_access/test.out
testsuite/tests/contrib/lkt_semantic/invalid_import/test.lkt
testsuite/tests/contrib/lkt_semantic/invalid_import/test.out
testsuite/tests/contrib/lkt_semantic/invalid_type_ref/test.lkt
testsuite/tests/contrib/lkt_semantic/invalid_type_ref/test.out
testsuite/tests/contrib/lkt_semantic/object_call/test.lkt
testsuite/tests/contrib/lkt_semantic/object_call/test.out

lkt_toolbox now raise an error if a declaration annotated with
@invalid doesn't emit any diagnostic, and conversely, it also checks
that a diagnostic is related to an @invalid declaration.
TN: UB03-005

Lkt: check for @invalid annotations in lkt_toolbox

---

langkit/templates/python_api/module_py.mako

Alias has been in place since Py 3.3, and minimum (test) version is 3.8, so I think we're safe
Figured I'd save everyone some time and PR it myself
Closes #580
(I'd have done 579 as well, but need your sign off on my proposed ~hack~workaround to do it)

Use collections.abc.Sequence as the alias is set to be removed
